AWSTemplateFormatVersion: '2010-09-09'
Description: Root stacks for VPC project

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-vpc-project-templates.s3.amazonaws.com/networking.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-vpc-project-templates.s3.amazonaws.com/security.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-vpc-project-templates.s3.amazonaws.com/compute.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        KeyName: !Ref KeyName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        BastionSecurityGroup: !GetAtt SecurityStack.Outputs.BastionSecurityGroup
        AppSecurityGroup: !GetAtt SecurityStack.Outputs.AppSecurityGroup

Outputs:
  VpcId:
    Value: !GetAtt NetworkStack.Outputs.VpcId
  BastionHost:
    Value: !GetAtt ComputeStack.Outputs.BastionHost
  ALB:
    Value: !GetAtt ComputeStack.Outputs.ApplicationLoadBalancer
