AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack for VPC project

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  KeyName:
    Type: String
    Description: EC2 Key Pair for SSH
    Default: my-key   # ✅ Added this line

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security.yml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        EnvironmentName: !Ref EnvironmentName

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./compute.yml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        BastionSG: !GetAtt SecurityStack.Outputs.BastionSG
        ALBSG: !GetAtt SecurityStack.Outputs.ALBSG
        PrivateInstanceSG: !GetAtt SecurityStack.Outputs.PrivateInstanceSG
        EnvironmentName: !Ref EnvironmentName
        KeyName: !Ref KeyName   # ✅ This ensures KeyName is passed to compute stack
