AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack - VPC project

Parameters:
  EnvironmentName:
    Type: String
    Default: my-vpc
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair for SSH access

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: compute.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        BastionSG: !GetAtt NetworkStack.Outputs.BastionSG
        ALBSG: !GetAtt NetworkStack.Outputs.ALBSG
        PrivateInstanceSG: !GetAtt NetworkStack.Outputs.PrivateInstanceSG
        KeyName: !Ref KeyName
